# Use the Secret in a Pod as Environment Variables
apiVersion: v1
kind: Pod
metadata:
  name: app-with-secret # edit
spec:
  containers:
  - name: my-app # edit
    image: nginx
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials # refer from your secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials # refer from your secret
          key: password
